name: PSScriptAnalyzer

on:
  push:
    branches: [master, beta, dev]
  pull_request:
    branches: [master, beta, dev]
  schedule:
    - cron: "32 20 * * 4"

jobs:
  psscriptanalyzer-security-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: ./src
          includeDefaultRules: true
          severity: '"Error", "Warning"'
          recurse: true
          settings: ./.vscode/PSScriptAnalyzerSettings.psd1
          output: pssanalyzer.sarif

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pssanalyzer.sarif
